// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/ppp3ppj/todo_htmx_nj/dto"
import "github.com/ppp3ppj/todo_htmx_nj/templates/components"

func Index(members []*dto.MemberCardDto) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\"><script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\" crossorigin=\"anonymous\"></script><script src=\"https://unpkg.com/htmx.org/dist/ext/class-tools.js\"></script><style>\n    @import url('https://fonts.googleapis.com/css2?family=Mitr');\n    body {\n      --bs-font-sans-serif: 'Mitr', sans-serif;\n      --bs-body-font-family: var(--bs-font-sans-serif);\n      --bs-font-monospace: 'VT323', monospace;\n    }\n    .demo.faded {\n      opacity:.3;\n    }\n    .demo {\n      opacity:1;\n      transition: opacity ease-in 2000ms;\n    }\n  </style><title>HTMX Go CRUD</title><script src=\"/static/htmx.min.js\"></script></head><body><div class=\"container text-center p-3\"><button hx-get=\"/add_member_modal\" hx-target=\"#add_member_modal_nj\" hx-trigger=\"click\" data-bs-toggle=\"modal\" data-bs-target=\"#add_member_modal_nj\" type=\"button\" class=\"btn btn-primary btn-lg m-2\">Add Member</button> <button hx-get=\"/add_member_10_rec\" hx-trigger=\"click delay:3s\" hx-swap=\"outerHTML\" hx-target=\"#members-list\" type=\"button\" class=\"btn btn-warning btn-lg m-2\">Add Random 10 Member</button><div id=\"add_member_modal_nj\" class=\"modal modal-blur fade\" style=\"display: none\" aria-hidden=\"false\" tabindex=\"-1\"><div class=\"modal-dialog modal-lg modal-dialog-centered\" role=\"document\"><div class=\"modal-content\"></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.MemberCards(members).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
